### ISSUE TITLE
update three brickify package to newest three.js version

### ISSUE THREAD

**Issue by mischkew** [platener/platener#25]
straight forward task.
see if we can merge easily.

otherwise pushing from branches with local newest three.js version is not possible

```
> Brickify@0.11.0 prepublish /Users/sven/Documents/workspace/platener
> npm test && npm run checkStyle


> Brickify@0.11.0 test /Users/sven/Documents/workspace/platener
> mocha --compilers coffee:coffee-script/register --recursive

/Users/sven/Documents/workspace/platener/node_modules/three/build/three.js:24
if ( self.requestAnimationFrame === undefined || self.cancelAnimationFrame === undefined ) {
     ^

ReferenceError: self is not defined
  at Object.<anonymous> (/Users/sven/Documents/workspace/platener/node_modules/three/build/three.js:24:6)
  at Module._compile (module.js:430:26)
  at Object.Module._extensions..js (module.js:448:10)
  at Module.load (/Users/sven/Documents/workspace/platener/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/sven/Documents/workspace/platener/src/plugins/newBrickator/pipeline/Grid.coffee:3:9)
  at Object.<anonymous> (/Users/sven/Documents/workspace/platener/src/plugins/newBrickator/pipeline/Grid.coffee:1:1)
  at Module._compile (module.js:430:26)
  at Object.loadFile (/Users/sven/Documents/workspace/platener/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/sven/Documents/workspace/platener/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/sven/Documents/workspace/platener/test/Brick/general.coffee:5:8)
  at Object.<anonymous> (/Users/sven/Documents/workspace/platener/test/Brick/general.coffee:1:1)
  at Module._compile (module.js:430:26)
  at Object.loadFile (/Users/sven/Documents/workspace/platener/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/sven/Documents/workspace/platener/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at /Users/sven/Documents/workspace/platener/node_modules/mocha/lib/mocha.js:216:27
  at Array.forEach (native)
  at Mocha.loadFiles (/Users/sven/Documents/workspace/platener/node_modules/mocha/lib/mocha.js:213:14)
  at Mocha.run (/Users/sven/Documents/workspace/platener/node_modules/mocha/lib/mocha.js:453:10)
  at Object.<anonymous> (/Users/sven/Documents/workspace/platener/node_modules/mocha/bin/_mocha:393:18)
  at Module._compile (module.js:430:26)
  at Object.Module._extensions..js (module.js:448:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:471:10)
  at startup (node.js:117:18)
  at node.js:951:3

npm ERR! Test failed.  See above for more details.

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/iojs/3.3.1/bin/iojs" "/usr/local/bin/npm" "run" "prepublish"
npm ERR! node v3.3.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! Brickify@0.11.0 prepublish: `npm test && npm run checkStyle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Brickify@0.11.0 prepublish script 'npm test && npm run checkStyle'.
npm ERR! This is most likely a problem with the Brickify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm test && npm run checkStyle
npm ERR! You can get their info via:
npm ERR!     npm owner ls Brickify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sven/Documents/workspace/platener/npm-debug.log
error: failed to push some refs to 'git@github.com:platener/platener.git'
```

**Comment by mischkew** [comment]
this needs to be resolved to push changes for #16
